# Generated by Django 4.2.9 on 2024-01-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
